export const careers = [
    'Tecnología en Dirección Comercial (virtual y presencial)',
    'Tecnología en Gestión Gastronómica (virtual dual)',
    'Tecnología en Gestión Humana (dual)',
    'Tecnología en Investigación Criminal y Ciencias Forenses',
    'Tecnología en Logística y Mercadeo',
    'Tecnología en Regencia de Farmacia (virtual)',
    'Tecnología en Seguridad y Salud en el Trabajo (virtual)',
    'Administración de Empresas modalidades presencial, virtual y dual',
    'Contaduría Pública (virtual y dual)',
    'Negocios Internacionales',
    'Administración Turística y Hotelera',
    'Economía',
    'Seguridad y Salud en el Trabajo (virtual)',
    'Derecho',
    'Ingeniería en Energía y Sostenibilidad',
    'Ingeniería Mecatrónica',
    'Ingeniería de Mercados',
    'Ingeniería Financiera',
    'Ingeniería Biomédica',
    'Ingeniería Industrial',
    'Ingeniería de Sistemas',
    'Enfermería',
    'Medicina',
    'Psicología',
    'Artes Audiovisuales',
    'Gastronomía y Alta Cocina',
    'Música',
    'Comunicación Social',
    'Licenciatura en Educación Infantil',
    'Literatura (virtual)',
  ];
  